// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfgeepsohzudlmsahlrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmZ2VlcHNvaHp1ZGxtc2FobHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzM0NzgsImV4cCI6MjA2Njg0OTQ3OH0.fIJ3hydmJgq-VxM6jzxZeEUwtuMRfyb8DEhq2hrPfK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});